version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ecom_admin
      POSTGRES_PASSWORD: asert2209
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"