# Generated by Django 5.1.5 on 2025-03-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
